(()=>{
const months=[
{id:'januar',name:'Január',intro:'Pokojnejšie obdobie je vhodné na kontrolu záhrady, údržbu náradia a plánovanie novej sezóny.',tasks:[['Skontroluj zimnú ochranu','Po vetre a snehu prever citlivé rastliny, opory a mladé stromčeky.','/blog.html'],['Prejdi uskladnenú úrodu','Priebežne vyraď poškodené plody a skontroluj podmienky skladovania.','/blog.html'],['Priprav náradie','Vyčisti, nabrús a oprav základné ručné náradie ešte pred jarným náporom.','/blog/priprava-zahradneho-naradia-na-zimu/'],['Naplánuj záhony','Zapíš si, čo sa osvedčilo a kam chceš presunúť jednotlivé plodiny.','/blog/jednoduchy-plan-vysadby-zahona/']]},
{id:'februar',name:'Február',intro:'Dni sa predlžujú a začína sa príprava prvých výsevov, stále však rozhoduje počasie.',tasks:[['Prvé výsevy v interiéri','Pri teplomilných plodinách sa riaď dĺžkou predpestovania a dostupným svetlom.','/temy/zahrada.html'],['Kontrola ovocných drevín','Rez rob iba pri vhodnom druhu, termíne a počasí; neponáhľaj sa pri silnom mraze.','/temy/zahrada.html'],['Kompost a materiál','Priprav si vyzretý kompost a materiál na jarné záhony.','/blog/kompost-bez-zapachu-rovnovaha-materialov/'],['Skontroluj dielňu','Doplň drobnosti a priprav pracovný priestor na jarné projekty.','/temy/dielna.html']]},
{id:'marec',name:'Marec',intro:'Začína sa aktívnejšia sezóna. Pôdu však spracuj až vtedy, keď nie je premokrená a lepivá.',tasks:[['Priprav záhony','Odstráň burinu, povrch prekypri a podľa potreby doplň kompost.','/temy/zahrada.html'],['Sej odolnejšie plodiny','Výber a termín prispôsob teplote pôdy a miestnej polohe.','/temy/zahrada.html'],['Skontroluj vyvýšené záhony','Doplň sadnutú výplň a oprav poškodené okraje.','/blog/cim-naplnit-vyvyseny-zahon-vrstvy/'],['Priprav zber vody','Pred jarnými dažďami vyčisti odkvapy, filter a sud.','/blog/dazdova-voda-jednoduchy-system-zo-suda/']]},
{id:'april',name:'Apríl',intro:'Pôda sa zohrieva, pribúda výsevov a výsadieb, no stále treba počítať s návratom chladu.',tasks:[['Sej podľa teploty pôdy','Reďkovka, hrášok či koreňová zelenina zvládnu chlad lepšie než teplomilné druhy.','/temy/zahrada.html'],['Mulčuj až vhodnú pôdu','Najprv nech sa pôda primerane zohreje a prekyprí.','/blog/mulcovanie-zahonov-bez-zbytocnych-chyb/'],['Kontroluj vlahu','Jarný vietor môže vysušovať povrch aj v chladnejšom počasí.','/blog/dazdova-voda-jednoduchy-system-zo-suda/'],['Dokonči opory a drobné stavby','Čo pripravíš teraz, nebudeš riešiť uprostred hlavnej sezóny.','/temy/dielna.html']]},
{id:'maj',name:'Máj',intro:'Rast je rýchly a po odznení rizika mrazov prichádza čas pre teplomilnejšie rastliny.',tasks:[['Sleduj posledné mrazy','Citlivé sadenice vysádzaj podľa miestnej predpovede a podmienok.','/temy/zahrada.html'],['Priprav opory','Paradajky a ďalšie vyššie rastliny vyviaž skôr, než sa začnú lámať.','/blog/opory-pre-paradajky-z-konarov/'],['Mulč a burina','Tenká vrstva vhodného mulču pomáha s vlahou aj burinou.','/blog/mulcovanie-zahonov-bez-zbytocnych-chyb/'],['Polievaj ku koreňom','Menej často a dôkladnejšie býva užitočnejšie než časté zmáčanie povrchu.','/blog/letne-polievanie-s-mensou-spotrebou/']]},
{id:'jun',name:'Jún',intro:'Záhrada ide naplno. Prioritou je voda, pravidelná kontrola rastlín a prvý väčší zber.',tasks:[['Zalievaj cielene','Kontroluj pôdu pod povrchom a smeruj vodu ku koreňovej zóne.','/blog/letne-polievanie-s-mensou-spotrebou/'],['Doplň mulč','Obnov miesta, kde sa vrstva rozpadla alebo odsunula.','/blog/mulcovanie-zahonov-bez-zbytocnych-chyb/'],['Zbieraj priebežne','Častý zber podporuje ďalšiu úrodu pri mnohých druhoch zeleniny.','/temy/zahrada.html'],['Sleduj opory','Po vetre alebo prudkom raste skontroluj väzby a konštrukcie.','/blog/opory-pre-paradajky-z-konarov/']]},
{id:'jul',name:'Júl',intro:'Horúčavy zvyšujú nároky na vodu. Pomáha tieň, mulč a práca v chladnejšej časti dňa.',tasks:[['Polievaj ráno alebo večer','Vyhni sa plytvaniu a sleduj skutočnú vlhkosť pôdy.','/blog/letne-polievanie-s-mensou-spotrebou/'],['Zachytávaj dažďovú vodu','Po búrkach skontroluj prepad, filter a čistotu nádoby.','/blog/dazdova-voda-jednoduchy-system-zo-suda/'],['Zbieraj a spracuj úrodu','Nenechávaj prezreté plody zbytočne na rastlinách.','/temy/zahrada.html'],['Udržuj priechody','Jasné chodníky a poriadok zjednodušia každodennú starostlivosť.','/blog/strkova-cesticka-medzi-zahonmi/']]},
{id:'august',name:'August',intro:'Zber pokračuje, no už sa dá myslieť na jesenné výsevy, pôdu a ďalšiu sezónu.',tasks:[['Zbieraj pravidelne','Kontroluj plody a odstraňuj poškodené časti.','/temy/zahrada.html'],['Využi uvoľnené záhony','Podľa podmienok môže prísť čas na krátke jesenné kultúry.','/temy/zahrada.html'],['Založ si poznámky','Zapíš si odrody, problémy a riešenia, ktoré sa tento rok osvedčili.','/blog/jednoduchy-dennik-zahrady/'],['Priprav kompost','Vyváž mokrý zelený materiál suchšou uhlíkatou zložkou.','/blog/kompost-bez-zapachu-rovnovaha-materialov/']]},
{id:'september',name:'September',intro:'September je stále čas zberu, ale zároveň sa začína príprava pôdy a výsadby na ďalšiu sezónu.',tasks:[['Zber a priebežné upratovanie','Zbieraj dozrievajúcu úrodu a odstraňuj choré či poškodené zvyšky rastlín.','/blog/jesenne-prace-v-zahrade-pred-zimou/'],['Ešte môžeš siať','Podľa lokálnych podmienok sa dajú využiť voľné záhony napríklad na reďkovku, rukolu alebo špenát.','/temy/zahrada.html'],['Priprav pôdu','Vyčisti uvoľnené záhony, jemne prekypri pôdu a podľa jej stavu pridaj vyzretý kompost.','/blog/kompost-bez-zapachu-rovnovaha-materialov/'],['Mysli na jesennú výsadbu','Priprav miesto pre ovocné stromčeky a cesnak; konkrétny termín prispôsob teplote pôdy a počasiu.','/blog/vysadba-ovocnych-stromov-na-jesen/']]},
{id:'oktober',name:'Október',intro:'Jesenná výsadba a príprava pred zimou sú v centre pozornosti, no termíny stále závisia od počasia.',tasks:[['Sadiť ovocné dreviny','Pri vhodnej pôde a počasí je jeseň dobrým obdobím na mnohé ovocné stromčeky.','/blog/vysadba-ovocnych-stromov-na-jesen/'],['Priprav cesnak','Termín výsadby prispôsob teplote pôdy, nie iba dátumu v kalendári.','/blog/sadenie-cesnaku-na-jesen/'],['Využi opadané lístie','Zdravé lístie môže poslúžiť na listovku alebo ako súčasť kompostu.','/blog/listovka-z-jesenneho-listia/'],['Skontroluj vodu a náradie','Pred mrazmi priprav sudy, hadice a náradie na zimu.','/blog/priprava-zahradneho-naradia-na-zimu/']]},
{id:'november',name:'November',intro:'Po hlavnom opade listov sa záhrada upokojuje. Prioritou je ochrana, voda a dokončenie príprav na zimu.',tasks:[['Dokonči výsadbu podľa podmienok','Pokiaľ pôda nie je zamrznutá a druh je vhodný na jesennú výsadbu.','/temy/zahrada.html'],['Vypusti citlivé nádoby','Sudy a hadice priprav podľa konštrukcie a odporúčania výrobcu.','/blog/dazdova-voda-jednoduchy-system-zo-suda/'],['Chráň mladé stromčeky','Podľa lokality rieš vietor, zver a poškodenie kmeňov.','/blog/vysadba-ovocnych-stromov-na-jesen/'],['Odlož čisté náradie','Suché, očistené a ošetrené náradie vydrží dlhšie.','/blog/priprava-zahradneho-naradia-na-zimu/']]},
{id:'december',name:'December',intro:'Záhrada odpočíva. Stačí pravidelná kontrola a pokojné plánovanie ďalšieho roka.',tasks:[['Kontroluj ochranu rastlín','Po vetre, snehu alebo prudkých zmenách teploty skontroluj kryty a opory.','/temy/zahrada.html'],['Striasaj ťažký mokrý sneh','Pri citlivých konároch postupuj jemne, aby sa nepolámali.','/temy/zahrada.html'],['Prejdi sklad a dielňu','Skontroluj úrodu, semená, náradie a materiál na ďalšiu sezónu.','/temy/dielna.html'],['Naplánuj jeden projekt','Vyber si jednu vec, ktorú chceš na jar postaviť alebo zlepšiť.','/blog.html']]}
];
function renderHome(){const wrap=document.getElementById('season-cards');if(!wrap)return;const m=months[new Date().getMonth()];const kicker=document.getElementById('season-kicker'),intro=document.getElementById('season-intro'),link=document.getElementById('season-calendar-link');if(kicker)kicker.textContent='TERAZ V ZÁHRADE · '+m.name.toUpperCase();if(intro)intro.textContent=m.intro;if(link)link.href='/kalendar.html#'+m.id;wrap.innerHTML=m.tasks.map((t,i)=>'<article class="season-card"><span>'+String(i+1).padStart(2,'0')+'</span><h3>'+t[0]+'</h3><p>'+t[1]+'</p><a href="'+t[2]+'">Pozrieť viac →</a></article>').join('')}
function markCalendar(){const m=new Date().getMonth();const card=document.querySelector('.calendar-month[data-month="'+m+'"]');if(card)card.classList.add('is-current')}
function calcBed(){const form=document.getElementById('raised-bed-calculator');if(!form)return;const n=id=>Math.max(0,Number(document.getElementById(id)?.value||0));const l=n('bed-length'),w=n('bed-width'),h=n('bed-height'),top=n('top-depth'),comp=Math.min(100,n('compost-share'));const total=l*w*(h/100),topDepth=Math.min(h,top),topVol=l*w*(topDepth/100),compost=topVol*(comp/100),soil=Math.max(0,topVol-compost),lower=Math.max(0,total-topVol),liters=total*1000,bag50=Math.ceil(liters/50);const fmt=v=>new Intl.NumberFormat('sk-SK',{maximumFractionDigits:2}).format(v);const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('result-total',fmt(total)+' m³');set('result-liters',fmt(liters)+' l');set('result-top',fmt(topVol)+' m³');set('result-soil',fmt(soil)+' m³');set('result-compost',fmt(compost)+' m³');set('result-lower',fmt(lower)+' m³');set('result-bags',bag50+' × 50 l')}
document.addEventListener('DOMContentLoaded',()=>{renderHome();markCalendar();const form=document.getElementById('raised-bed-calculator');if(form){form.addEventListener('submit',e=>{e.preventDefault();calcBed()});form.addEventListener('input',calcBed);calcBed()}})
})();